# Generated by Django 3.2.4 on 2021-06-09 10:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(max_length=30)),
                ('neighborhood_location', models.CharField(max_length=30)),
                ('neighborhood_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='1920x1080')),
                ('occupants_count', models.IntegerField(null=True)),
            ],
        ),
    ]
