# Generated by Django 3.2.4 on 2021-06-09 11:51

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField(max_length=70)),
                ('post_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('post_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='1920x1080')),
                ('post_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hood.neighborhood')),
            ],
        ),
    ]
