# Generated by Django 3.2.4 on 2021-06-09 12:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hood', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bs_name', models.CharField(max_length=30)),
                ('about', tinymce.models.HTMLField()),
                ('bs_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bs_email', models.EmailField(max_length=254)),
                ('bs_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='1920x1080')),
                ('bs_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='hood.neighborhood')),
            ],
        ),
    ]
